name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Authenticate into Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          
    - name: Set Project
      run: gcloud config set project ${{ secrets.GCLOUD_PROJECT }}

    - name: Build and Push Image
      run: gcloud builds submit --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/nodeapp:latest .
      
    - name: Deploy
      run: kubectl apply -f ./deployment.yml
